name: Build and Submit to App Store
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          /usr/local/bin/pod install

      - name: Set Xcode signing
        run: |
          # 配置 Xcode 项目的签名
          xcodebuild -project JenkinsTest.xcodeproj -scheme JenkinsTest CODE_SIGN_IDENTITY="Apple Development: Yaohui Fu (ZAN29V44ST)"  -allowProvisioningUpdates
          
      - name: Build and Archive
        run: |
            xcodebuild -workspace JenkinsTest.xcworkspace -scheme JenkinsTest -sdk iphoneos archive -archivePath JenkinsTest.xcarchive

      - name: Export Archive
        run: |
          xcodebuild -exportArchive -archivePath JenkinsTest.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath JenkinsTest.ipa

      - name: Upload to App Store
        uses: actions/upload-artifact@v2
        with:
          name: JenkinsTest
          path: JenkinsTest.ipa

  submit:
    needs: build
    runs-on: macos-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: JenkinsTest
          path: JenkinsTest.ipa

      - name: Set up App Store Connect
        uses: devbotsxyz/appstore-connect-cli-action@v1
        with:
          appstore-connect-private-key: ${{ secrets.APPSTORE_CONNECT_PRIVATE_KEY }}
          appstore-connect-issuer-id: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
          appstore-connect-key-id: ${{ secrets.APPSTORE_CONNECT_KEY_ID }}
          appstore-connect-app-id: YourAppID

      - name: Upload to App Store Connect
        run: |
          appstore-connect upload JenkinsTest.ipa --wait-for-processing
